### ISSUE TITLE
Add hovering effect on social media icons at footer

### ISSUE THREAD

**Issue by YatharthaRana** [minhaj-313/Facts-Website#1]

**Comment by YatharthaRana** [comment]
Please assign me this under Hacktober fest
@minhaj-313

**Comment by minhaj-313** [comment]
> _No description provided._

Start doing but do quality code.
first give the star to this repository and follow me. please follow all the guidelines of Hacktoberfest.

**Comment by minhaj-313** [comment]
> Please assign me this under Hacktober fest @minhaj-313

already assigned you @YatharthaRana

**Comment by YatharthaRana** [comment]
> > Please assign me this under Hacktober fest @minhaj-313
> 
> already assigned you @YatharthaRana

yeah I mean add labels of hacktober fest
