### ISSUE TITLE
new category section for facts of specific type

### ISSUE THREAD

**Issue by amansgith** [minhaj-313/Facts-Website#17]
i would like to add a section of cards with slider having title and image of category of facts
and add the same to navigation bar menu text with dropdown...
please assign me this issue to work upon

**Comment by minhaj-313** [comment]
@amansgith yes you can start.
First, you need to give start to this repository and follow me >> Fork this Repositor >> Then clone it >> do quality code >> Make PR.
Thank You

**Comment by amansgith** [comment]
Ok thanks

**Comment by amansgith** [comment]
Problem:
i have seen that the footer is not settled at the bottom and large gap is between navigation bar and the bulb image and the responsive design is also requires some fix..

Solution:
i have fixed the issues

**Comment by minhaj-313** [comment]
ok you can send a PR
