### ISSUE TITLE
Dark theme missing

### ISSUE THREAD

**Issue by YatharthaRana** [minhaj-313/Facts-Website#2]
Please assign me this issue under Hacktoberfest and I will add dark theme mode on your website

**Comment by minhaj-313** [comment]
Start doing but do quality code.
first give the star to this repository and follow me. please follow all the guidelines of Hacktoberfest.

**Comment by YatharthaRana** [comment]
Yeah I will try my best to add some quality codes

Hacktoberfest accepted level too !!

**Comment by minhaj-313** [comment]
> Yeah I will try my best to add some quality codes
> 
> Hacktoberfest accepted level too !!

Sure
