### ISSUE TITLE
Update Navbar and Search bar

### ISSUE THREAD

**Issue by CodeWithBishal** [minhaj-313/Facts-Website#20]
Hi I want to update the **Navbar** by making it sticky and add search functionality to the **Search Bar**

**Comment by minhaj-313** [comment]
> Hi I want to update the **Navbar** by making it sticky and add search functionality to the **Search Bar**

Great, Go ahead @CodeWithBishal . You can Start

First you need to give star to this repository and follow me then you will start
Thank you.
