### ISSUE TITLE
Improvements is required in some areas 

### ISSUE THREAD

**Issue by front-runner-sd** [minhaj-313/Facts-Website#24]
1. Footer section not spanning the whole area.
![image](https://user-images.githubusercontent.com/91823106/194716515-3b199eb5-1b4c-4ac4-9951-fa75f2293d89.png)
2. Too much distance between hero and navbar
![image](https://user-images.githubusercontent.com/91823106/194716597-881c4b6b-6a40-4e36-bd0f-8612e8efab87.png)
3. The opening animation of the nav bar is not smooth unlike the closing animation.

**Comment by front-runner-sd** [comment]
Can I work in this issues?

**Comment by minhaj-313** [comment]
@front-runner-sd  You Can Start Working on this issue.
First you need to like this repository and then follow me and then Start working.

**Comment by front-runner-sd** [comment]
Well the issues were fixed by someone else. I'm closing this issue as it is not required right now
