### ISSUE TITLE
Update Readme File add some extra features.

### ISSUE THREAD

**Issue by minhaj-313** [minhaj-313/Facts-Website#3]

**Comment by itzROHIT-coder** [comment]
I can do that,could you assign me this?

**Comment by Samarthasbhat** [comment]
I can do that , but extra features in readme.md file??

**Comment by minhaj-313** [comment]
@Samarthasbhat  You can Start Doing Please do attractive work.
First you need to give star to this repository and follow me after you start working on project you can read rules in CONTRIBUTING.md

> I can do that , but extra features in readme.md file??

**Comment by minhaj-313** [comment]
> I can do that,could you assign me this?

You can work on another project in my repository their is one project name as Portfolio-1 their are a lots of issue you can solve their
