### ISSUE TITLE
Correcting fact 21

### ISSUE THREAD

**Issue by Ericchuk** [minhaj-313/Facts-Website#36]
I would like to correct fact 21, it contains 2 fact and 2 diffent github  ID.
I propose that this issue be assigned to me to seperate them.

**Comment by minhaj-313** [comment]
@Ericchuk Yes you can do it.

first give start and follow me then solve issue.
Thank You

**Comment by Ericchuk** [comment]
should I proceed with it? I am asking cos I saw closed

**Comment by minhaj-313** [comment]
@Ericchuk Yes you can do it,
I closed it because I already assigned it to you.
you can do it.
