### ISSUE TITLE
Add New Banner to Readme File

### ISSUE THREAD

**Issue by chiragkhatri19** [minhaj-313/Facts-Website#4]
Hello, I am a graphics designer and I wanna create a custom made banner for the Readme File, If you want me to do that assign me this issue and please include HacktoberFest labels too

**Comment by minhaj-313** [comment]
> Hello, I am a graphics designer and I wanna create a custom made banner for the Readme File, If you want me to do that assign me this issue and please include HacktoberFest labels too

Start doing 
First you need to give star to this repository and follow me after you start working on project you can read rules in CONTRIBUTING.md
