### ISSUE TITLE
Navbar Fix

### ISSUE THREAD

**Issue by Ayushhgupta39** [minhaj-313/Facts-Website#51]
There is no need of a toggler button while on large and Medium Screens. 
After fixing this, The toggler will be present on small screens like Mobile phones only, and on large and medium sized screens, we will be having a Complete Navbar. 

Assign me this and add Hacktoberfest and Hacktoberfest-accepted labels.

**Comment by minhaj-313** [comment]
First Give Star to this repository and follow me. Connect me on linkedIn, then start doing it
 Thank You

**Comment by Ayushhgupta39** [comment]
Why is that necessary? Everyone here is to contribute. If you like the work then accept the PR, if not then simply don't.
